on:
  release:
    types:
      - published

name: release

jobs:
  release-linux:
    name: upload Linux releases to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1

      - name: build wheels
        run: make dist-pyrage

      - name: publish
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: target/wheels/

  release-macos:
    name: upload macOS releases to PyPI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1

      - name: build wheels
        run: |
          make env
          source env/bin/activate
          maturin build --release --strip --universal2

      - name: publish
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: target/wheels/
